export { default as Blog } from './Blog'
export { default as Content } from './Content'
export { default as CV } from './CV'
export { default as Footer } from './Footer'
export { default as Header } from './Header'
export { default as Home } from './Home'
export { default as Intro } from './Intro'
